### ISSUE TITLE
movies2.csv

### ISSUE THREAD

**Issue by ericvd-ucb** [ls88-openscienceconnector/LS-88-Assignments#1]
Chris can you post movies2.csv ?
( I cant find mine!)

**Comment by chrispyles** [comment]
I deleted the original movies.csv file and replaced it with the 3 MB version (formerly movies2.csv). If you pull from GitHub again ([https://tinyurl.com/ls88datahub](https://tinyurl.com/ls88datahub)) and run the file 1.2-movies.ipynb, everything should work
